### ISSUE TITLE
Heap corruption 0xC0000374

### ISSUE THREAD

**Issue by syntroniks** [BrianHumlicek/J2534-Sharp#1]
Something is causing heap corruption. I tested this by adding extra calls to hJ2534MessageArray.ToMessageArray. Calling this function more often resulted in a heap corruption code sooner.

Triggering garbage collection makes this happen _VERY_ fast.

Minimal example with GC:
```var interfaceList = SAE.J2534.APIFactory.GetAPIList();
var selectedInterface = interfaceList.First(a => a.Name == "Intrepid neoVI Fire/Red");
var api = SAE.J2534.APIFactory.GetAPI(selectedInterface.Filename);
var dev = api.GetDevice();
GC.Collect();
while (true) { Thread.Sleep(5); };

The program '[0x1B4] Example.exe' has exited with code -1073740940 (0xc0000374).

**Comment by syntroniks** [comment]
Sample code:
```
      var interfaceList = SAE.J2534.APIFactory.GetAPIList();
      var selectedInterface = interfaceList.First(a => a.Name == "Intrepid neoVI Fire/Red");
      var api = SAE.J2534.APIFactory.GetAPI(selectedInterface.Filename);
      var dev = api.GetDevice();
      var chan = dev.GetChannel(SAE.J2534.Protocol.CAN, SAE.J2534.Baud.ISO15765_500000, SAE.J2534.ConnectFlag.CAN_ID_BOTH);
      chan.ClearMsgFilters();
      var filter = new SAE.J2534.MessageFilter() { FilterId = 0, FilterType = SAE.J2534.Filter.PASS_FILTER, Mask = new byte[] { 0, 0, 0x0, 0x0 }, Pattern = new byte[] { 0, 0, 0x0, 0x00 } };
      chan.StartMsgFilter(filter);
      while (true)
      {
        var msgs = chan.GetMessages(200, 10);
        if (msgs.Result == SAE.J2534.ResultCode.FAILED)
          continue;
        foreach (var msg in msgs.Messages.Where(m => m.Data.Length > 0 && ((m.RxStatus & SAE.J2534.RxFlag.START_OF_MESSAGE) == 0)))
        {
          var arbid = msg.Data[2] << 8 | msg.Data[3];
          Console.WriteLine($"0x{arbid:X03}: {BitConverter.ToString(msg.Data.Skip(4).ToArray())}");
        }
      }

**Comment by syntroniks** [comment]
I modified `GetDevice` so it would only call `PTOpen` (not construct and return a new `Device`). The heap corruption still exists.

**Comment by syntroniks** [comment]
I ended up modifying some of the Heap* types to dispose differently. Seems to work -- PR incoming.

**Comment by Alshain01** [comment]
I was having the same issue, incorporating the pull request into my project did correct it.

**Comment by Tremo1984** [comment]
Attempting managed execution inside OS Loader lock.

APIFactory.GetAPI(FileName)
Any help with the above tried disabling loader lock witch throws a debugging fault

**Comment by syntroniks** [comment]
@Tremo1984 That looks like a separate issue. Could you create a separate issue to track what you're seeing?

**Comment by BrianHumlicek** [comment]
Sorry about my delayed response.  I have experienced this myself and found the issue.  I will release a new version to correct it in a few days.

**Comment by BrianHumlicek** [comment]
I checked in a fix for this and rebuild the package.  Update your package in nuget and verify this solves the issue.

**Comment by syntroniks** [comment]
👍 Solves the issue, things are working very well now. TY
