### ISSUE TITLE
SetProgrammingVoltage missing VOLTAGE_OFF and SHORT_TO_GROUND settings

### ISSUE THREAD

**Issue by stiv2k** [BrianHumlicek/J2534-Sharp#17]
When using J2534-Sharp to communicate using SCI in the Engine "B" configuration, there are certain times when the programming voltage should be enabled to 20V and then off again to resume normal communications.

I'm able to turn on the 20V strobe to initiate programming mode, but the library is lacking the ability to turn it back off. The SAE J2534 defines the following voltage values that should be passed to SetProgrammingVoltage():

Definition | Value
-----------|---------
Programming Voltage | 0x00001388 (5000 mV) to 0x00004E20 (20000 mV)
SHORT_TO_GROUND | 0xFFFFFFFE
VOLTAGE_OFF | 0xFFFFFFFF

I can't pass 0xFFFFFFFF because SetProgrammingVoltage() requires an int type for the voltage value. The WINAPI prototype uses long type for the voltage, so I think it's just a matter of changing the type on the C# side.

```C#
// activate and stable Vpp voltage
m_j2534Interface.SetProgrammingVoltage(Pin.PIN_12, 20000);
var v = m_j2534Interface.MeasureProgrammingVoltage();
Console.WriteLine("programming voltage is " + (v / 1000).ToString("F2")); // programming voltage is 20.00

// loop until we ge a reply 
var readData = new List<byte>();
if (ReceiveMsg(ref readData))
{
    // shut down the Vpp
    m_j2534Interface.SetProgrammingVoltage(Pin.PIN_12, 12000);

    v = m_j2534Interface.MeasureProgrammingVoltage();
    Console.WriteLine("programming voltage is " + (v / 1000).ToString("F2")); // programming voltage is 12.00
   // doesn't work, and leaves the pass thru device in an unresponsive state until I re-insert the USB cable
   // should be passing 0xFFFFFFFF instead
}
```

**Comment by BrianHumlicek** [comment]
Sorry I've been slow to respond.  I think when I wrote that I assumed you would be able to pass those hex values directly in.  As it turn out, it complains if you try, but I figured out a way to make it happen.

SetProgrammingVoltage(Pin.PIN_12, unchecked((int)0xFFFFFFFE));

I will make some changes so you don't have to do this, but in the short term, this should get you by.

Brian

**Comment by stiv2k** [comment]
I can confirm that using ```unchecked((int)0xFFFFFFFF))``` works. Thanks!
