### ISSUE TITLE
Invalid option '7.1' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default

### ISSUE THREAD

**Issue by autoprog** [BrianHumlicek/J2534-Sharp#3]
Hi,
my test code j2534, with vcs2013.
I have interface vci usb with J2534 ok.

I add in projects  Form for test, compiling error, 

see:
Error	1	Invalid option '7.1' for /langversion; must be ISO-1, ISO-2, 3, 4, 5 or Default
	C:\...\J2534-Sharp-master\src\CSC	J2534-Sharp

file CSC not found !

if ignore error:

![image](https://user-images.githubusercontent.com/5191545/71091836-b0925080-2184-11ea-929f-a2a0fb01db96.png)

how to test with windows form?

thanks
Carlos.

**Comment by BrianHumlicek** [comment]
I think you need to use Visual Studio 2017 or later to use C# 7.1

**Comment by autoprog** [comment]
Hi,
thanks,
Carlos.
