### ISSUE TITLE
Sending or receiving problem

### ISSUE THREAD

**Issue by jwdsoft** [BrianHumlicek/J2534-Sharp#4]
I'm using the example code you put in the readme the code runs fine without error and voltage shows 24v as expected but the message is not sent on the can bus and also it doesn't receive any messages from the bus.
The interface is working fine since I use it with another software which uses J2534 and it works fine reading and writing.
I don't know what is the problem and how to solve it.
I thought at the begining that it was a baudrate issue so I also hooked a logic analyzer on the bus but the bus doesn't have any activity
Please help me solve this issue

**Comment by BrianHumlicek** [comment]
Reading the device voltage does not result in a message being sent or received.  The voltage is measured by the device and reported back to the API.

If you are having trouble sending or receiving messages, please include what protocol and what configuration you are using, as well as the message.

Brian

**Comment by jwdsoft** [comment]
Yes I know the voltage is not result in a message being sent or received I'm pointing that to let you know the API read my device just fine.
I used you example code without any editing
`
![image](https://user-images.githubusercontent.com/3936079/80322609-e66fd180-8815-11ea-94dd-3d2c33f47560.png)
`
and I set my receiving can bus device to 500kbaud and it doesn't receive anything same as the logic analyzer
But I'm planning to use also different protocols once the ISO15765 works fine

**Comment by bradm3** [comment]
Hey Brian, I really appreciate you putting this library together, really awesome work and a true time saver. 

I have a test app I have written in python using a j2534 dll that works well with 2 of my interfaces(cardaq/openport). However when implementing this library I cannot receive messages. 

I have the filter set with the appropriate flow control and can send a RDBI request to one of the modules which works fine. However when sending it to other modules I cannot get it to return the START_OF_MESSAGE. All I see is one message being returned with  RxStatus: 0:TX_MSG_TYPE 3:TX_INDICATION but then nothing else follows after that. Any pointers? Thanks much!

**Comment by jwdsoft** [comment]
Hello @bradm3 
Can you tell me which python j2534 library worked fine for you since I'm having the same issue not receiving data even on python library
Can you send me your working python example and library please
Thank you
