### ISSUE TITLE
Better example for reading messages

### ISSUE THREAD

**Issue by tek1229** [BrianHumlicek/J2534-Sharp#7]
Hi, and thanks for the work you've done here.. I am by no means a programmer, I just goof around a little as spare time allows..  

Given that I am no means a professional at this, I cannot seem to figure out how to read the response or simply read the canbus..  If this is too simple a question just let me know.. I don't want a handout, lol but I can't see the forest thru the trees.. 

I have started with your example and I can send a vin request command ok, I can request coolant temp, etc.. The message is going thru as desired and I can see the ecu response on the bus but I am unable to figure out how to see what the response is in this program.. I am just using command line for now so a Console.Writeline example would be perfect if you could help me out a little..
Using the code below, 

Channel.SendMessage(new byte[] { 0x00, 0x00, 0x07, 0xE0, 0x01, 0x05 });
 GetMessageResults Response = Channel.GetMessage();

Tried Console.WriteLine("received data is "+ Response) ;   // This doesn't work..
tried Console.WriteLine("Incoming message is " + Response.Result); // doesn't work either.
tried Console.WriteLine("Incoming message is " + Response.Messages); // doesn't work either.
Lost count of the multiple variations I've tried without success.. 

Now I can pause the code and I can look at the locals and look in Result and I can see  the byte responses that I am expecting, I just don't see how to get them out.. 

Hopefully this is a simple problem, but not too simply, I don't want to be roasted too badly, lol...

If  this problem is fixed, one other question I just started looking into is that it looks like the CAN formatting is done for me.. If I send 01 05 it sends 7E0 02 01 05 so I can see it adds the message size parameter for me..  Is there any way for me to turn this off? Right now I am using am elm327 and I do have a use for sending slightly different packets of data with an abnormal message size byte.. I haven't looked too hard for this so I apologize if it's staring me in the face, just spent a couple hours working on the first problem and I hadn't run into a solution for the second.. lol..

Thanks again for the work you've done already, this is looking like some fun..

**Comment by BrianHumlicek** [comment]
The answer to you first question I think would look like this

GetMessageResults Response = Channel.GetMessage();
ConsoleWriteLine("Incoming message is " + Bitconverter.ToString(Response.Messages[0].Data));

I recommend reading up on arrays and how they work.

For your next question, I think that behavior is coming from your 2534 device, not my API.  I think what you are looking for is a raw CAN connection vs. ISO15765.  My examples use ISO15765 as it is the most common implementation today.  The ISO protocol adds the length bytes and it is done within the 2534 device, not J2534-Sharp.  What you need to do is connect with one of the base CAN protocols, and you will get what your asking.

I will look at updating the examples to include something that reports a basic message.

Brian

**Comment by tek1229** [comment]
Thanks for the assistance.. Trying this now, wasn't working at my work computer..
Was only getting 00-00-07-E0 as an incoming message..

I changed GetMessageResults Response = Channel.GetMessage();   to

GetMessageResults Response = Channel.GetMessages(2,10);

and then I changed the zero to a 1 in the Messages[] field.. Now it's showing the response..

Not sure if this is just this desktop that is glitching.. I'll get there.. I'll definitely read up on arrays, I kinda know about arrays but not in C#... the format is strange to me, Thanks again!!
