### ISSUE TITLE
GetAPIinfo() not found

### ISSUE THREAD

**Issue by autoprog** [BrianHumlicek/J2534-Sharp#9]
hi,
I have other code j2534 c# running ok,
now with VS2019 c#, test J2534-Sharp in my interface.
install Nuget: Install-Package J2534-Sharp -Version 1.0.0-CI00026 =ok
project vs ok
probelms:
string DllFileName =  APIFactory.GetAPIinfo().First().Filename; no have it in code.

my test: DllFileName = @"MY.dll"; in forder = ok call send frame.

string DllFileName = APIFactory.GetAPIList().First().Filename; it **select firt ok**

how to, creat device List for, selecte manual whats device use ?

example: 
 Channel Channel = APIFactory.GetAPI( mylist[3],,,);

thanks;
Carlos.

**Comment by BrianHumlicek** [comment]
GetAPIInfo will enumerate the registry.  If you dont have anything there, First() will throw an exception.  It sounds like what you need to do is,
var API = APIFactory.GetAPI(@"MY.dll");
var device = API.GetDevice...;
var channel = device.GetChannel...

**Comment by autoprog** [comment]
hi brian,
in pc, have more interface J2534 instaled... need select one.
I need  List<J2534> Devices = J2534.ListDevices();, will select

ok,
now other problems with path
see,
DllFileName = @"C:\\Program Files\\BOSSA\driver\\MY.dll";  = OK

DllFileName = @"C:\Program Files(x86)\FOLDER1\\folder2\\MY32.dll";  = error, dll not found

my system 64bit/x64

more, running send frame 7E0.08.02.01.00.00.00.00.00.00 =ok

thnks,
Carlos.

**Comment by BrianHumlicek** [comment]
I can only assume the reason for the dll not found error is because it doesn't exist, and I can't fix that.

**Comment by autoprog** [comment]
hi,
my teste, I paste in folder, problems path ( visual studio)
more importante is devicelist in **registry**.
I get divices in registry, will test whats is connected on pc.

thanks,
Carlos.

**Comment by autoprog** [comment]
hi Brian,
problems 1: **device lis Solved**

 APIInfo[] info = APIFactory.GetAPIList();
           for (int i=0;i< info.Length; i++)
            {
                rtb_main.Text += inf[i].Name + " - " + inf[i].Filename + "\r\n"; show list device = ok
            }

problems path danied continue...
test manuals
C:\Program Files(x86)\xx\zz\MY.dll = NOT FOUND
C:\Program Files\xx\zz\MY.dll = OK
C:\YY\MY.dll = OK

problems C:\Program Files(x86) it folder.

thaks,
Carlos.
